var price=Number(prompt("Enter the amount"))
if(price<1000)
    document.writeln("<h2>NO Discount<br>Purchase for ",1000-price," more for discount")
else if(price==1000 || price<2500)
    document.writeln("<h2>5% Discount")
else if(price==2500 || price<5000)
    document.writeln("<h2>8% Discount")
else if(price>=5000)
    document.writeln("<h2>10% Discount")
